### ISSUE TITLE
选择下载后显示Windows 找不到文件 ‘D：win‘。请确定文件名是否正确后，再试一次。

### ISSUE THREAD

**Issue by zhuoerbuqun929** [user1121114685/Wallpaper_Engine#16]
选择下载后显示Windows 找不到文件 ‘D：win‘。请确定文件名是否正确后，再试一次。
![image](https://user-images.githubusercontent.com/111233087/184539291-1d3a7d70-e678-4e14-804e-4670e149bfed.png)

**Comment by user1121114685** [comment]
重新选择下壁纸软件路径，尽量不要有奇怪符号 空格或者中文。
