### ISSUE TITLE
win10打开就闪退

### ISSUE THREAD

**Issue by windfsy** [user1121114685/Wallpaper_Engine#2]
win10打开就闪退，目录是放对了，用管理员也不行

**Comment by user1121114685** [comment]
> win10打开就闪退，目录是放对了，用管理员也不行

没有安装chrome

**Comment by conan4803** [comment]
> 
您好，我chrome用的绿色版，运行后直接闪退，我抓了下截图意思是找不到chrome的路径么？这种情况应该怎么处理，谢谢
#
![Snipaste_2021-12-13_10-56-52](https://user-images.githubusercontent.com/3960732/145745549-78ae1339-ff09-4b6f-b27c-51151a8b2938.png)

**Comment by user1121114685** [comment]
> > 
> 
> 您好，我chrome用的绿色版，运行后直接闪退，我抓了下截图意思是找不到chrome的路径么？这种情况应该怎么处理，谢谢
> 
> ![Snipaste_2021-12-13_10-56-52](https://user-images.githubusercontent.com/3960732/145745549-78ae1339-ff09-4b6f-b27c-51151a8b2938.png)

安装chrome即可。绿色版倒是打开思路了

**Comment by conan4803** [comment]
> > > 
> > 
> > 
> > 您好，我chrome用的绿色版，运行后直接闪退，我抓了下截图意思是找不到chrome的路径么？这种情况应该怎么处理，谢谢
> > ![Snipaste_2021-12-13_10-56-52](https://user-images.githubusercontent.com/3960732/145745549-78ae1339-ff09-4b6f-b27c-51151a8b2938.png)
> 
> 安装chrome即可。绿色版倒是打开思路了

您好，能否加个自定义chrome路径功能？绿色版嘛，就是不想安装。感谢

**Comment by Resunny** [comment]
> 

你添加环境变量就行了
