### ISSUE TITLE
431960 连接不存在

### ISSUE THREAD

**Issue by kathycxz** [user1121114685/Wallpaper_Engine#7]
麻烦看一下，报错是什么原因，谢谢。
![微信截图_20220610195341](https://user-images.githubusercontent.com/54104884/173059237-53a12987-b07d-42b9-88de-ce1a005ca390.png)

**Comment by user1121114685** [comment]
这个只是一个提示，后面不是已经建立了连接了吗？，以后运行就没这个提示了。
